modLoader = "javafml"
loaderVersion = "[${forgeDependencyVersion},)"
license = "MIT"

[[mods]]
modId = "ephemera"
version = "${version}"
displayName = "Ephemera"
logoFile = "icon.png"
authors = "beholderface"
description = '''
Assorted hexcasting things.
'''

[[dependencies.ephemera]]
modId = "forge"
mandatory = true
versionRange = "[${forgeDependencyVersion},)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.ephemera]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},]"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.ephemera]]
modId = "architectury"
mandatory = true
versionRange = "[${architecturyVersion},)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.ephemera]]
modId = "hexcasting"
mandatory = true
versionRange = "[${hexcastingVersion},)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.ephemera]]
modId = "hexal"
mandatory = true
versionRange = "[${hexalVersion},)"
ordering = "BEFORE"
side = "BOTH"