# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.0.9
_src_path: gh:FallingColors/hexdummy
author: beholderface
capitalize_platforms: false
classname: Ephemera
default_branch: main
description: Assorted hexcasting things.
display_name: Ephemera
github_repo: ephemera
hexcasting_version: 0.10.3
homepage_url: https://beholderface.github.io/ephemera
initial_mod_version: 0.0.1
java_version: 17
license: MIT
mappings_name: Yarn
modid: ephemera
package: net.beholderface.ephemera
sources_url: https://github.com/beholderface/ephemera
